using Plots 

import PALEOboxes as PB
import PALEOmodel
import NCDatasets

##################################
# Read and plot output generated by 
# P_O_romglb_save_grid.jl
####################################


gr(size=(400, 400))
# gr(size=(600, 600))

output_folder_name = "P_O_romglb_baseline_20231218"
# dropbox_output_dir = "/home/sd336/Dropbox/BACE_OOEOAE/DainesLiOverleaf/OOEOAE_base/P_O_romglb_shelf_20231116" # will need to create this manually
dropbox_output_dir = joinpath(@__DIR__, "../../figures/P_O_romglb_shelf_20231116")
output_figures_dir = joinpath(
    dropbox_output_dir, 
    output_folder_name,
)

# netcdf files are large so don't put them in shared Dropbox
netcdf_dir = joinpath(
    # "/home/sd336/Dropbox/BACE_OOEOAE_large/DainesLiOverleaf/OOEOAE_base/P_O_romglb_shelf_20231116", 
    dropbox_output_dir,
    "P_O_romglb_save_grid_20231218",
)


P_total_modern = 3.4e15 # mol P for P_norm=1.0
P_burial_level=4e10 # mol P yr-1

expts_table = [
    (
        "burial_shelves6_BioProdPrest_Martin_Ozaki2011_0p23_0p25",  (0.23, 0.25),
    ),
    (
        "burial_shelves6_BioProdPrest_Martin_Ozaki2011_0p15_0p6", (0.15, 0.6),
    ),
    # (
    #     "burial_shelves6_BioProdPrest_Martin_Ozaki2011_0p15_0p8", (0.15, 0.8), :green,
    # ),
    (
        "burial_shelves6_BioProdPrest_Martin_Ozaki2011_0p05_0p75", (0.05, 0.75),
    ),
]

isdir(output_figures_dir ) || mkdir(output_figures_dir)


p_Pnullcline = plot(;
    # title="P burial $P_burial_level", 
    xlabel="P_total / modern", ylabel="pO2 (PAL)", 
    bottom_margin = 1Plots.mm, right_margin = 1Plots.mm,
    cbar=false,
    legend=:topright,
)

# the simplest way to use consistent colors is to refer to them by index in the current "cycle"
# https://discourse.julialang.org/t/way-to-get-default-color-order-in-plots-jl/12643/11
coloridx = 1

for (filenameroot,  O2_U_target) in expts_table
# (filenameroot,  O2_U_target)  = expts_table[1]
    local target_O2_U_min, target_O2_U_max = O2_U_target

    cube_file = joinpath(netcdf_dir, filenameroot*"_cube.nc");

    NCDatasets.NCDataset(cube_file, "r") do ds
        
        O2PAL = 0.21*PB.Constants.k_moles1atm

        group_fluxOceanBurial = ds.group["fluxOceanBurial"]
        P_total_grid = Array(group_fluxOceanBurial["P_total_grid"])
        O2_grid = Array(group_fluxOceanBurial["O2_grid"])

        flux_total_P = Array(group_fluxOceanBurial["flux_total_P"])
        
        contour!(
            p_Pnullcline,
            P_total_grid./P_total_modern, O2_grid./O2PAL, flux_total_P';
            levels=[P_burial_level],
            color=coloridx, # index of color in current "cycle"
            # label="target ($target_O2_U_min, $target_O2_U_max)", # doesn't work
        )
        # "empty plot trick" to add to legend
        plot!(
            p_Pnullcline,
            [100, 100], [100, 100];
            label="target ($target_O2_U_min, $target_O2_U_max)",
            color=coloridx,
        )

    end

    global coloridx += 1

end

plot!(
    p_Pnullcline;
    xlim=(0.0, 5.0), ylim=(0.0, 1.5),
    legend=:none,
)
display(p_Pnullcline)
savefig(p_Pnullcline, joinpath(output_figures_dir, "Pnullcline_Summary.svg"))